ft010 edit category
akademia-envelo-3/meetek-front pull request #106
Opened 2023-02-16 11:22 UTC by piodaw

2023-02-20 07:05 UTC, EMEZYK requested changes

2023-02-20 07:05 UTC, EMEZYK commented on src/app/features/categories/shared/interfaces/categories.interfaces.ts
> +export interface updateCategory {
nazwy interfejsow z wielkiej litery

2023-02-20 07:05 UTC, EMEZYK commented on src/app/features/categories/store/categories.store.ts
> +import { map, Observable, switchMap } from 'rxjs';
tą linijkę wynieś wyżej

2023-02-20 07:05 UTC, EMEZYK commented on src/app/features/categories/store/categories.store.ts
> +      tapResponse(
o, tego operatora jeszcze nie znam :D

2023-02-20 07:05 UTC, EMEZYK commented on src/app/features/categories/categories.component.ts
>      // brak taska?
jeśli mamy brak taska, to od razu dodawajmy taki task i wrzućmy tutaj link, zeby nam nie umknelo (nizej ta sama sugestia)

2023-02-20 07:05 UTC, EMEZYK commented on src/app/features/categories/categories.component.ts
> +    this.openDialog('Edytuj kategorię', 'Wpisz nazwę kategorii', 'Zapisz', true, true, category.id, category.name)
a dlaczego tu dwa razy true?

2023-02-27 11:37 UTC, akademiaEnvelo requested changes

2023-02-27 11:37 UTC, akademiaEnvelo commented on src/app/features/categories/categories.component.ts
> +    editId?: number,
ta metoda openDialog wyrasta na jakiegos potworka z tymi roznymi parametrami. Przeróbmy to na obiekt konfiguracyjny, będzie czytelniejszy podczas samego wywoływania metody

2023-02-27 11:37 UTC, akademiaEnvelo commented on src/app/features/categories/shared/interfaces/categories.interfaces.ts
> +export interface updateCategory {
\+ 1

2023-02-28 10:25 UTC, EMEZYK approved these changes

2023-02-28 10:39 UTC, akademiaEnvelo approved these changes

2023-03-01 14:30 UTC, merged