feat: added routing paths
akademia-envelo-3/meetek-front pull request #26
Opened 2023-01-09 12:41 UTC by damiankubecki

In auth.module.ts and home.module.ts I added objects with paths related to corresponding modules

2023-01-09 12:52 UTC, damiankubecki commented
Po konsultacji z zespołem zdecydowaliśmy, aby obiekt ze ścieżkami znajdował się wewnątrz pliku auth.module.ts/home.module.ts zamiast w osobnym pliku.

2023-01-11 10:12 UTC, akademiaEnvelo requested changes

2023-01-11 10:12 UTC, akademiaEnvelo commented on src/app/features/home/home.module.ts
> +};
oznaczmy object literal jako `as const`, dzięki temu będziemy mieli bardziej wyizolowane typy

2023-01-11 10:12 UTC, akademiaEnvelo commented on src/app/features/auth/auth.module.ts
> +};
jak niżej :)

2023-01-11 10:12 UTC, akademiaEnvelo commented on src/app/features/home/home.module.ts
> +export const homePaths = {
```typescript
export const homePaths = {
  //...
} as const;
```
sprawdź jakie są różnice w typie homePaths przed i po dodaniu `as const`

2023-01-11 10:12 UTC, akademiaEnvelo commented on src/app/features/home/home.module.ts
> +export const homePaths = {
dobra praktyką jest też zapisywanie słowników lub stałych w zapisie `UPPERCASED`

```
const HOME_PATHS = {
 DEFAULT: ''
}
```

dzięki temu widzimy w kodzie że zmienna której używamy jest stałą wartością nie zmieniająca się w czasie.

2023-01-11 10:55 UTC, akademiaEnvelo approved these changes

2023-01-11 10:56 UTC, piodaw approved these changes

2023-01-11 10:59 UTC, merged