FT018 - feat: added endpoints
akademia-envelo-3/meetek-front pull request #27
Opened 2023-01-09 12:59 UTC by lkrzysztoff

this commit adds endpoints in file shared/api/endpoints.ts. FT018

2023-01-10 08:51 UTC, damiankubecki reviewed
Bardzo dobrze napisany kod. Clean code u autora tego dzieła na najwyższym poziomie, wszystko jasne i czytelne.

2023-01-10 11:35 UTC, damiankubecki approved these changes
Bardzo dobrze napisany kod. Clean code u autora tego dzieła na najwyższym poziomie, wszystko jasne i czytelne.

2023-01-11 10:13 UTC, akademiaEnvelo requested changes

2023-01-11 10:13 UTC, akademiaEnvelo commented on src/app/shared/api/endpoints.ts
> +}
zamiast używania enumów użyjmy object literal oznaczonego jako as const

```typescript
export const endpoints = {
  events: '/events'
} as const;

export type Endpoints = typeof endpoints;
```

https://www.youtube.com/watch?v=jjMbPt_H3RQ - tutaj film fajnie wyjaśniający dlaczego enumy to czyste zło

2023-01-11 10:57 UTC, lkrzysztoff commented on src/app/shared/api/endpoints.ts
> +}
poprawione

2023-01-11 14:13 UTC, akademiaEnvelo approved these changes

2023-01-11 14:13 UTC, merged