FT021-add-store-for-sections
akademia-envelo-3/meetek-front pull request #31
Opened 2023-01-12 13:12 UTC by EMEZYK

@akademia-envelo-3/meetek-frontend

2023-01-12 14:37 UTC, piodaw requested changes

2023-01-12 14:37 UTC, piodaw commented on src/app/features/section/store/section.service.ts
> +    return this.http.delete<Section>(BASE_URL + `/sections/${sectionId}/users/${userId}`);
Popraw linki na literal type `${BASE_URL}/sections/...`

2023-01-12 14:37 UTC, piodaw commented on src/app/features/section/store/section.service.ts
> +  constructor(private http: HttpClient) {}
Używajmy inject zamiast constructor

2023-01-13 07:55 UTC, EMEZYK commented on src/app/features/section/store/section.service.ts
> +    return this.http.delete<Section>(`${BASE_URL}/sections/${sectionId}/users/${userId}`);
do tych dwóch metod nie wrzucałam jeszcze logiki, ze względu na to, że dopóki nie mam backendu, a json server nie obsluży mi tego zapytania, to nie mam jak tego przetestować;  widoczne endpointy i metody są już dogadane z backendem

2023-01-13 12:31 UTC, piodaw approved these changes
gituwa

2023-01-13 12:42 UTC, akademiaEnvelo requested changes

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/features/section/store/section.actions.ts
> +export const sectionsApiActions = createActionGroup({
dla grupy akcji proponuje uzycie zapisu `SectionsApiActions` jako ze jest to słownik

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/features/section/store/section.effects.ts
> +      }),
dodajmy tutaj implicit return w funkcji strzalkowej by zachowac spojnos w ramach pliku

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/features/section/store/section.effects.ts
> +          }),
czemu zagnieżdżamy tutaj ten operator?

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/features/section/store/section.effects.ts
> +          }),
mamy nie spójność w zagniezdzaniu operatorów w ramach pliku z efektami. Dążmy do posiadania jak najmniejszej ilośći zagnieżdzeń o ile to możliwe z poziomu działania kodu ofc

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/features/section/store/section.reducer.ts
> +    })
pobranie ze store to nie akcja a selektor

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/features/section/store/section.service.ts
> +const BASE_URL = environment.API_URL;
nie odnośnimy sie bezpośrednio do pliku `environment` tylko wstrzyujemy url za pomocą InjectionToken zarejestrowanego w `app.module`

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/features/section/store/section.service.ts
> +    return this.http.delete<Section>(`${BASE_URL}/sections/${sectionId}/users/${userId}`);
dodajmy zatem taska do backlogu na to zadanie na to oraz zostawmy tutaj numer taska w komentarzu

2023-01-13 12:42 UTC, akademiaEnvelo commented on src/app/app.module.ts
> +import { ToastrModule } from 'ngx-toastr';
czy dodanie toastów to odpowiedzialność tego taska?

2023-01-13 13:57 UTC, EMEZYK commented on src/app/features/section/store/section.service.ts
> +    return this.http.delete<Section>(`${BASE_URL}/sections/${sectionId}/users/${userId}`);
ok, task dodany

2023-01-13 14:01 UTC, EMEZYK commented on src/app/app.module.ts
> +import { ToastrModule } from 'ngx-toastr';
Nie jest to odpowiedzialnością tego taska, więc wyrzucam

2023-01-16 10:28 UTC, akademiaEnvelo approved these changes

2023-01-16 10:42 UTC, merged