feat: added section-card component
akademia-envelo-3/meetek-front pull request #33
Opened 2023-01-13 12:39 UTC by damiankubecki

This commit adds section card component

2023-01-16 09:00 UTC, EMEZYK requested changes

2023-01-16 09:00 UTC, EMEZYK commented on src/app/core/theme.component.ts
> +      console.log('activation...');
zbędne console.log możemy usunąć

2023-01-16 09:00 UTC, EMEZYK commented on src/app/features/section/shared/section-card/section-card.component.scss
> +}
do ustalenia z grupą - czy przechodzimy na konwencję BEM

2023-01-16 09:00 UTC, EMEZYK commented on src/app/features/section/shared/section-card/section-card.component.ts
> +  @Input() isActive!: boolean;
co powiesz na to, żeby zamiast używania tutaj ! , podać wartości domyślne?  / ew. skonfigurować ts.config.json:"compilerOptions": {
  ///
  ,
  "strictPropertyInitialization":false
}  ?

2023-01-16 09:20 UTC, damiankubecki commented on src/app/core/theme.component.ts
> +      console.log('activation...');
Te console.log'i znajdują się w theme componencie i mają na celu lepiej zobrazować działanie komponentu dla osoby, która w przyszłości będzie chciała z niego korzystać. Wydaje mi się, że w tym miejscu mogą się legalnie pojawić, bo być może jeszcze nie każdy ogarnia działanie outputów - tak jak ja dzień wcześniej 😎

2023-01-16 09:36 UTC, damiankubecki commented on src/app/features/section/shared/section-card/section-card.component.ts
> +  @Input() isActive!: boolean;
Hmm wydaje mi się, że nie ma potrzeby przypisywać tym polom wartości domyślnych, ponieważ są wymagane, więc i tak zostaną przekazane. Moim zdaniem ten `!` wyróżnia inputy, które są `required` i nie mamy potrzeby patrzenia na templatkę

2023-01-16 09:52 UTC, EMEZYK requested changes

2023-01-16 09:52 UTC, EMEZYK commented on src/app/features/section/shared/section-card/section-card.component.scss
> +
a moze w sumie skorzystamy tutaj z materiala? https://material.angular.io/components/card/overview

2023-01-16 10:31 UTC, akademiaEnvelo approved these changes

2023-01-16 10:35 UTC, EMEZYK commented on src/app/features/section/shared/section-card/section-card.component.ts
> +  @Input() isActive!: boolean;
ok, przekonales mnie kolego

2023-01-17 08:19 UTC, EMEZYK approved these changes

2023-01-17 14:15 UTC, merged