feat: add logic and styles for list of the section members
akademia-envelo-3/meetek-front pull request #36
Opened 2023-01-17 13:19 UTC by EMEZYK

ft022-feat-wyswietlanie-listy-uczestnikow-sekcji--meetek-envelo.netlify.app

@KamilWojkowskiEnvelo 
@akademia-envelo-3/meetek-frontend

2023-01-17 13:28 UTC, EMEZYK commented
Info:

Odpalając lokalnie bazę, pod adresem:   /section/{idSekcji}/members   i dynamicznie podstawiając id sekcji, powinna wyświetlić się lista jej uczestników

2023-01-18 11:26 UTC, akademiaEnvelo requested changes

2023-01-18 11:26 UTC, akademiaEnvelo commented on src/app/features/home/home.component.ts
> +  imports: [RouterOutlet, CommonModule],
czemu importujemy tutaj `commonmodule`

2023-01-18 11:26 UTC, akademiaEnvelo commented on src/app/features/section/shared/list/list-item/member-list-item.component.ts
> +  @Input() initials!: string;
wzmocnijmy selektor jak dodajemy wymagane inputy

2023-01-18 11:26 UTC, akademiaEnvelo commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +  imports: [MatListModule, MemberListItemComponent, CommonModule],
nie musimy importować całego commonmodule, wystarczy te dyrektywy i składowe których potrzebujemy

2023-01-18 11:26 UTC, akademiaEnvelo commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +        this.sectionId = NaN;
czemu NaN?

2023-01-18 11:26 UTC, akademiaEnvelo commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +    return user.firstName.charAt(0) + user.lastName.charAt(0);
nie wiem czy macie ustalone, ale może warto rozważyć używanie template literal?

2023-01-18 11:26 UTC, akademiaEnvelo commented on src/app/features/section/subpages/section-members.component.ts
> +// to do: dodać wyszukiwarkę oraz menu górne
jak dodajemy taki komentarz to wrzućmy numer taska z linkiem do niego

2023-01-18 13:09 UTC, piodaw requested changes

2023-01-18 13:09 UTC, piodaw commented on src/app/core/theme.component.scss
> +}
Używajmy stałych : `@import 'breakpoints.scss';` i w kodzie `@include breakpoint('laptop' lub 'mobile')`

2023-01-18 13:09 UTC, piodaw commented on src/app/features/section/shared/list/member-list/member-list.component.scss
> +}
Używajmy stałych : `@import 'breakpoints.scss';` i w kodzie `@include breakpoint('laptop' lub 'mobile')`

2023-01-18 13:09 UTC, piodaw commented on src/app/features/section/subpages/section-members.component.scss
> +}
Używajmy stałych : `@import 'breakpoints.scss';` i w kodzie `@include breakpoint('laptop' lub 'mobile')`

2023-01-20 08:17 UTC, damiankubecki commented on src/app/features/section/shared/list/list-item/member-list-item.component.ts
> +  selector: 'app-members-list-item',
W selektorze brakuje obowiązkowych input'ów `name` oraz `initials`. Teraz przy wywołaniu komponentu, nie wyświetli nam się żaden błąd, a chcemy, żeby nie dało się go utworzyć bez przekazania danych

2023-01-20 08:22 UTC, damiankubecki commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +  usersOfSection$!: Observable<User[] | undefined>;
Ta sama sytuacja - jeśli oczekujemy jakiegoś input'a i nie możemy bez niego wyświetlić komponentu to uwzględnijmy go w selektorze :)

2023-01-20 08:26 UTC, damiankubecki commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +  selector: 'app-members-list',
Dlaczego używamy `member-list` przy nazwach plików, a selektor jest `members-list`?

2023-01-23 08:16 UTC, damiankubecki approved these changes

2023-01-23 09:24 UTC, piodaw requested changes

2023-01-23 09:24 UTC, piodaw commented on src/app/features/home/home.component.ts
> +  }
ten kod jest potrzebny? A jeśli jest to jeśli i tak loadSections jest publiczne to wrzuć to `this.sectionStore.dispatch(SectionActions.getSections())` od razu do ngOnInit

2023-01-23 10:08 UTC, piodaw approved these changes

2023-01-23 11:42 UTC, akademiaEnvelo requested changes

2023-01-23 11:42 UTC, akademiaEnvelo commented on src/app/core/theme.component.scss
> +@import 'breakpoints.scss';
proponuję używać `use` by nie duplikować importów danego arkusza

2023-01-23 11:42 UTC, akademiaEnvelo commented on src/app/features/home/home.component.ts
> +  styles: [``],
jeśli nie mamy tutaj żadnych styli, wyrzućmy tę linijkę

2023-01-23 11:42 UTC, akademiaEnvelo commented on src/app/features/section/shared/list/member-list/member-list.component.html
> +      [initials]="getInitials(user)"></app-members-list-item>
a może po prostu przekażmy tam user'a i komponent już ogarnie na jego podstawie inicjaly i wyciągnie sobie imie? z tego co widzę jest to komponent domenowy więć możemy przekazać domenowego propsa dla niego

2023-01-23 11:42 UTC, akademiaEnvelo commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +  private activeRoute = inject(ActivatedRoute);
najpiewr injecty w komponencie, potem reszta definicji pól

2023-01-24 08:06 UTC, akademiaEnvelo approved these changes

2023-01-24 08:06 UTC, akademiaEnvelo commented on src/app/features/section/shared/list/list-item/member-list-item.component.ts
> +  }
te dwie metody powtarzają się z tym co robi @jBachanek-02 dodajmy proszę do backlogu task techniczny na zbudowanie dwóch `pipe` na to

2023-01-26 10:55 UTC, merged