FT024 feat: serwis do obsługi toastów
akademia-envelo-3/meetek-front pull request #58
Opened 2023-01-23 12:58 UTC by EMEZYK

Info:
działanie toasta można zobaczyć,  np. wpisujac niepoprawne dane logowania usera

@KamilWojkowskiEnvelo 
@akademia-envelo-3/meetek-frontend

2023-01-23 13:25 UTC, damiankubecki approved these changes
Bardzo dobry kod koleżanko

2023-01-24 07:55 UTC, akademiaEnvelo requested changes

2023-01-24 07:55 UTC, akademiaEnvelo commented on src/app/shared/services/toastr-facade.service.ts
> +  public toastr = inject(ToastrService);
nie do końca teraz działa to jak fasada, bo nadal jesteśmy uzależnieni od zewnętrznej biblioteki, chodzi tutaj o to by dodać konkretne metody takie jak `error` `success`, `warning` itp, które przyjmą taki kształt

```typescript
private toastr = inject(ToastrService);

public error(message, heading) {
   this.toastr.error(message, heading);
}
```

a następnie w aplikacji będziemy odwoływać się już do konkretnych metod, a nie będzie interesowała nas implementacja ich, jedyne czego potrzebujemy to przekazanie odpowienich argumentów, a w przypadku toastów to oczywistymi parametrami jest wiadomosc w toast lub opcjonalnie  naglowek toasta

2023-01-24 07:55 UTC, akademiaEnvelo commented on src/app/shared/services/toastr-facade.service.ts
> +  public toastr = inject(ToastrService);
przy czym przy projektowaniu fasady nie musimy implementować od razu wszystkich metod, które chcemy "opakować" w twoim przypadku wystarczy tylko error, jak ktoś będzie chciał użyć np. success, to wtedy to doda

2023-01-24 13:44 UTC, piodaw approved these changes

2023-01-26 06:27 UTC, akademiaEnvelo approved these changes
dobra fasada!

2023-01-26 09:03 UTC, merged