FT038 - feat: added token interceptor
akademia-envelo-3/meetek-front pull request #60
Opened 2023-01-24 12:49 UTC by damiankubecki

This commit adds token interceptor

2023-01-24 15:54 UTC, piodaw approved these changes

2023-01-26 08:08 UTC, piodaw approved these changes

2023-01-26 08:23 UTC, jBachanek-02 approved these changes

2023-01-26 12:13 UTC, EMEZYK requested changes

2023-01-26 12:13 UTC, EMEZYK commented on src/app/shared/interceptors/token.interceptor.ts
> +export class TokenInterceptor implements HttpInterceptor {
niepotrzebnie wpisujesz 'export', skoro ponizej eksportujesz provider

2023-01-26 12:13 UTC, EMEZYK commented on src/app/app.module.ts
> +import { TokenInterceptorProvider } from '@shared/interceptors/token.interceptor';
dodaj index.ts, zeby skrocic sciezke importu

2023-01-26 12:16 UTC, damiankubecki commented on src/app/shared/interceptors/token.interceptor.ts
> +export class TokenInterceptor implements HttpInterceptor {
przepraszam

2023-01-26 12:24 UTC, EMEZYK requested changes

2023-01-26 12:24 UTC, EMEZYK commented on src/app/shared/interceptors/token.interceptor.ts
> +export class TokenInterceptor implements HttpInterceptor {
wybaczę jak poprawisz

2023-01-26 12:25 UTC, damiankubecki commented on src/app/shared/interceptors/token.interceptor.ts
> +export class TokenInterceptor implements HttpInterceptor {
poprawione

2023-01-26 12:29 UTC, EMEZYK approved these changes

2023-01-27 13:07 UTC, akademiaEnvelo approved these changes

2023-01-27 13:43 UTC, merged