Ft008 feat stworzenie formularza do dodawania sekcji
akademia-envelo-3/meetek-front pull request #62
Opened 2023-01-25 08:22 UTC by piodaw

2023-01-26 14:24 UTC, EMEZYK requested changes

2023-01-26 14:24 UTC, EMEZYK commented on .vscode/settings.json
>  }
to chyba niekoniecznie powinno się tutaj pojawić? :)

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/auth/form/form.component.html
> +    <button mat-raised-button color="primary" [disabled]="loginForm.invalid">Zaloguj się</button>
dobrą praktyką jest ustawiać rzeczy od waznych, do mniej wazniejszych, czyli  wtym przypadku klasę ustawmy na koncu

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/section/store/section.effects.ts
>          //to do: tutaj ma się pojawić toast; task nr FT024: https://github.com/akademia-envelo-3/meetek-front/issues/34
tu juz mozesz dodac ten toast

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/section/subpages/section-form/form/form.component.html
> +        <div class="input">
zmienilabym nazwę klasy na bardziej deskryptywną, bo w tym momencie mozna ja latwo pomylic z el, html;
moze 'input-wrapper' albo 'form-input'?

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/section/shared/interfaces/section-form.interface.ts
> +}
skoro wiemy, ze będzie tylko 1 organizator, to zmienmy nazwę na Organizer (interfejsy piszmy tez z wielkiej litery);  

dlaczego wszystkie pola są opcjonalne?

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/section/shared/interfaces/section-form.interface.ts
> +export interface AddNewSection {
moze lepiej uzyc nazwy NewSection?  add wskazuje na działanie, bardziej do funkcji

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/section/store/section.actions.ts
> +import { AddNewSection } from '../shared/interfaces/section-form.interface';
zgodnie z naszą konwencją, oddzielajmy importy corowe, od tych naszych;  

pamiętaj też o index.ts, zeby skrocic te importy

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/section/store/section.service.ts
>  import { API_URL } from '@core/env.token';
jw.

2023-01-26 14:24 UTC, EMEZYK commented on src/app/features/section/subpages/section-form/form/form.component.html
> +    <form [formGroup]="newSectionForm" (submit)="createSection()">
zamiast (submit) ->   (ngSubmit)

"ngSubmit ensures that the form doesn’t submit when the handler code throws (which is the default behaviour of submit) and causes an actual http post request. '

2023-01-30 08:08 UTC, piodaw commented on src/app/features/auth/form/form.component.html
> +    <button mat-raised-button color="primary" [disabled]="loginForm.invalid">Zaloguj się</button>
moim zdaniem bardziej czytelnie jest jeśli klasę mamy na pierwszym miejscu

2023-01-30 10:40 UTC, akademiaEnvelo requested changes

2023-01-30 10:40 UTC, akademiaEnvelo commented on src/app/features/section/shared/interfaces/section-form.interface.ts
> +export interface organizer {
typo, `Organizer`

2023-01-30 10:40 UTC, akademiaEnvelo commented on src/app/features/section/shared/interfaces/section-form.interface.ts
> +export interface NewSection {
czemu prefix New a nie samo `Section`?

2023-01-30 10:40 UTC, akademiaEnvelo commented on src/app/features/section/store/section.effects.ts
> +      }),
przesuńmy tę sideeffect do `tap` zaraz po operatorze `map`

2023-01-30 10:40 UTC, akademiaEnvelo commented on src/app/features/section/subpages/section-form/form/validators/form.validators.ts
> +  return null;
dodajmy whitewspace po blokach kodu jak `if`, chyba że tak macie

2023-01-30 11:27 UTC, piodaw commented on src/app/features/section/shared/interfaces/section-form.interface.ts
> +export interface NewSection {
Pod `Section` mamy typy do wszystkich danych z sekcji dlatego wolałem stworzyć nowy w którym potrzebujemy tylko 3 typów

2023-01-30 13:03 UTC, akademiaEnvelo approved these changes

2023-01-31 08:21 UTC, damiankubecki commented on src/app/core/store/user.service.ts
> +      },
do usunięcia, mamy już interceptor

2023-01-31 09:30 UTC, EMEZYK approved these changes
Poprawione, daję approve :)

2023-02-02 08:01 UTC, jBachanek-02 approved these changes

2023-02-08 10:26 UTC, merged