Ft031 utworzenie modali
akademia-envelo-3/meetek-front pull request #78
Opened 2023-01-26 16:00 UTC by lkrzysztoff

2023-01-27 08:57 UTC, EMEZYK requested changes

2023-01-27 08:57 UTC, EMEZYK commented on src/app/core/theme.component.ts
> +    <app-example-dialog></app-example-dialog>
to tutaj w theme powinienes wywolac te 2 dialogi, oddzielnie input z dialogiemm, oddzielnie d ialogz buttonami; czyli logikę z example-dialog, przeniesc tutaj, a tamten folder wywalic

2023-01-27 08:57 UTC, EMEZYK commented on src/app/shared/ui/modals/example dialog/example-dialog.component.ts
> +}
interfejsy wynośmy do oddzielnego pliku

2023-01-27 08:57 UTC, EMEZYK commented on src/app/shared/ui/modals/example dialog/example-dialog.component.ts
> +import { CancelConfirmDialogComponent } from '../quit-section-dialog/cancel-confirm-dialog.component.ts';
dla kazdego folderu, zgodnie z nasza konwencja, tworzmy plik index.ts zeby skrocic sciezki importow

2023-01-27 08:57 UTC, EMEZYK commented on src/app/shared/ui/modals/input dialog/input-dialog.component.html
> +        name="dialogData" />
dobra praktyka jest ustawiac rzeczy od wazniejszych do mniej waznych;  klasę przesunęłabym na koniec,a zaczelabym od ngModel

2023-01-27 08:57 UTC, EMEZYK commented on src/app/shared/ui/modals/input dialog/input-dialog.component.ts
> +import { FormsModule } from '@angular/forms';
importy zewnętrzne oddzielamy spacją od tyc naszych wewnątrznych

2023-01-27 08:57 UTC, EMEZYK commented on src/app/shared/ui/modals/example dialog/example-dialog.component.html
> +      <button mat-raised-button (click)="openDialog2()">Dialog z przyciskami</button>
jeszcze jedna kwestia - jesli nazwa folderu sklada sie z wiecej niz 1 członu, to oddzielamjmy przez myslnik

2023-01-27 09:11 UTC, damiankubecki commented on src/app/shared/ui/modals/input dialog/input-dialog.component.ts
> +import { FormsModule } from '@angular/forms';
*enterem 😉

2023-01-27 09:39 UTC, damiankubecki commented on src/app/shared/ui/modals/quit-section-dialog/cancel-confirm-dialog.component.ts.ts
> +  constructor( public dialog:MatDialog, @Inject(MAT_DIALOG_DATA) public data: { text: string }) {}
dialog powinien być `private`

2023-01-27 09:39 UTC, damiankubecki commented on src/app/shared/ui/modals/quit-section-dialog/cancel-confirm-dialog.component.ts.ts
> +}
proszę użyć prettiera w tym pliku

2023-01-27 09:41 UTC, damiankubecki commented on src/app/shared/ui/modals/quit-section-dialog/cancel-confirm-dialog.component.ts.ts
> +  selector: 'app-quit-section-dialog[text]',
czy używamy gdzieś `text`?

2023-01-27 09:45 UTC, damiankubecki commented on src/app/shared/ui/modals/input dialog/input-dialog.component.html
> +        placeholder="{{data.inputLabelText}}"
tutaj możemy użyć `[placeholder]="data.inputLabelText"`, wtedy od razu widać, że do `placeholder` przekazujemy wartość z ts

2023-01-27 09:49 UTC, lkrzysztoff commented on src/app/shared/ui/modals/quit-section-dialog/cancel-confirm-dialog.component.ts.ts
> +  selector: 'app-quit-section-dialog[text]',
nie, to przypadkowo tam zostało

2023-01-27 09:50 UTC, damiankubecki commented on src/app/shared/ui/modals/quit-section-dialog/cancel-confirm-dialog.component.html
> +    <button mat-button class="cancel-confirm-dialog__confirm-btn success">POTWIERDŹ</button>
`text content` w tych buttonach powinen być napisany bez uppercase. Uppercase w naszych buttonach powinien być ustawiony w stylach globalnych (`text-transform: uppercase;`) - @jBachanek-02

2023-01-27 09:56 UTC, damiankubecki commented on src/app/shared/ui/modals/input dialog/input-dialog.component.ts
> +  constructor(public dialog: MatDialog, @Inject(MAT_DIALOG_DATA) public data: DialogData) {}
przyjęliśmy w projekcie strategię wstrzykiwania zależności za pomocą `inject`, więc do wyrzucenia z `constructor` + dialog powinien być `private`

2023-01-27 10:00 UTC, damiankubecki commented on src/app/shared/ui/modals/input dialog/input-dialog.component.scss
> +  color: var(--text);
zalecam dodanie `transition` - tak jak mają wszystkie buttony w naszej pięknej aplikacji

2023-01-27 13:46 UTC, EMEZYK requested changes

2023-01-27 13:46 UTC, EMEZYK commented on src/app/shared/ui/modals/index.ts
> +export * from './quit-section-dialog/cancel-confirm-dialog.component.ts';
ogólnie jeszcze jedna rzecz - ten folder i sam komponent nazwałabym 'confirm-dialog' , bo on nie tylko odnosi się do opuszczania sekcji, będziemy go reużywać

2023-01-27 15:14 UTC, EMEZYK approved these changes

2023-01-27 15:19 UTC, jBachanek-02 approved these changes

2023-01-30 11:17 UTC, akademiaEnvelo approved these changes

2023-01-31 08:29 UTC, merged