feat: added pipes
akademia-envelo-3/meetek-front pull request #81
Opened 2023-01-27 14:15 UTC by lkrzysztoff

this commit adds two pipes for transforming user data

2023-01-30 09:22 UTC, piodaw requested changes

2023-01-30 09:22 UTC, piodaw commented on src/app/shared/pipes/full-name.pipe.ts
> +  transform(value: UserResponse): string {
typ string nie jest potrzebny

2023-01-30 09:22 UTC, piodaw commented on src/app/shared/pipes/initials.pipe.ts
> +  transform(value: UserResponse): string {
jw

2023-01-30 11:09 UTC, damiankubecki commented on src/app/shared/pipes/full-name.pipe.ts
> +  transform(value: UserResponse) {
`value` niewiele mówi, więc dałbym po prostu `user`

2023-01-30 11:09 UTC, damiankubecki commented on src/app/shared/pipes/initials.pipe.ts
> +  transform(value: UserResponse) {
tutaj też `user` zamiast `value`

2023-01-31 10:06 UTC, damiankubecki approved these changes

2023-01-31 12:39 UTC, akademiaEnvelo approved these changes

2023-01-31 13:31 UTC, piodaw approved these changes

2023-01-31 13:32 UTC, merged