FT014 Wyswietlenie widoku wszystkich sekcji
akademia-envelo-3/meetek-front pull request #82
Opened 2023-01-30 09:50 UTC by jBachanek-02

2023-01-30 09:55 UTC, jBachanek-02 commented
Widok https://deploy-preview-82--meetek-envelo.netlify.app/sections

2023-01-30 10:58 UTC, piodaw requested changes

2023-01-30 10:58 UTC, piodaw commented on src/app/features/home/home.module.ts
>  import { SectionMembersComponent } from '../section/subpages/section-members.component';
rozdziel importy wewnętrzne od zewnętrznych

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.html
> +        <app-section-card [name]="'Rowerzyści'" [numberOfMembers]="24" [isActive]="true"></app-section-card> -->
usuń zakomentowane linijki

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.html
> +</div>
to też nie jest potrzebne

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.scss
> +}
korzystaj z globalnych breakpointów

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +  public readonly allSections$: Observable<Section[]> = this.store.select(selectAllSections);
typ i public readonly jest zbędne

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +  private service = inject(SectionService);
service nie jest używany

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +  public loadSections() {
defaultowo wszystkie są public więc dodawanie tego jest zbędne

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +  }
nawigację dodaj w templatce jako routerLink zamiast na click

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +      this.isActive = false;
logika powinna być połączona z ngrx

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
tego nie powinno być

2023-01-30 10:58 UTC, piodaw commented on src/styles.scss
> +  --text:#000;
już jest ta zmienna

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +import { HOME_PATHS } from '../home';
import powinien być niżej

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +import { NgIf, AsyncPipe, JsonPipe, NgForOf } from '@angular/common';
jsonpipe nie jest potrzebny

2023-01-30 10:58 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +  imports: [MatButtonModule, MatInputModule, MatIconModule, SectionCardComponent, NgIf, NgForOf, AsyncPipe, JsonPipe],
jw

2023-01-30 11:17 UTC, jBachanek-02 commented on src/app/features/section/sections.component.html
> +</div>
juz usunięte

2023-01-30 11:18 UTC, jBachanek-02 commented on src/app/features/section/sections.component.ts
> +  public readonly allSections$: Observable<Section[]> = this.store.select(selectAllSections);
ok

2023-01-30 11:18 UTC, jBachanek-02 commented on src/app/features/section/shared/list/member-list/member-list.component.ts
> +      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
wyskakuje błąd i nie mogę dac commita

2023-01-30 11:36 UTC, jBachanek-02 commented on src/app/features/section/sections.component.ts
> +  }
ok

2023-01-30 11:54 UTC, jBachanek-02 commented on src/styles.scss
> +  --text:#000;
rozwiążę konflikt

2023-01-31 09:17 UTC, piodaw requested changes

2023-01-31 09:17 UTC, piodaw commented on src/app/features/section/sections.component.html
> +          routerlink="section/:id"
żeby to mogło działać tu musisz przekazać id sekcji

2023-01-31 09:17 UTC, piodaw commented on src/app/features/section/sections.component.html
> +<a routerLink="section/add">
korzystaj ze stałych

2023-01-31 09:17 UTC, piodaw commented on src/app/features/section/sections.component.html
> +  <button mat-fab color="accent" aria-label="Example icon button with a add icon">
aria-label do wywalenia

2023-01-31 14:29 UTC, jBachanek-02 commented on src/app/features/section/sections.component.html
> +<a routerLink="section/add">
zrobiłem na click

2023-02-03 09:18 UTC, EMEZYK requested changes

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.html
> +<main>
dodajmy plik index.ts i skróćmy ścieżki importów

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.scss
> +main{
ogólnie ten komponent wrapujący, powinien być scrollowalny i powinien byc identyczny, jak w przypadku wyświetlania uczestników sekcji; możemy wgl wydzielić sam ten wrapper z uczestników sekcji, do oddzielnego komponentu i tutaj jego użyć, bo w sumie będzie nam potrzebny w kilku miejscach

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.ts
> +    NgForOf,
o, nie znam takiej dyrektywki :D ale chyba nawet jej tutaj nie uzywasz, do usuniecia

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.html
> +    <br />
wydaje mi się, ze ten br jest tu zbędny;  jesli chcesz zwiekszyc odleglosc, to lepiej uzyc margin

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.html
> +        (activation)="handleActivation(section.id)"
obecnie buttony aktywuj i dezatywuj zmianiają swoją wartość dopiero po odświeżeniu strony

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.html
> +        (modification)="handleModification(section.id)"
po kliknięciu w modyfikuj, nie przenosi nas na odpowiedni route

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.scss
> +  font-family: var(--roboto);
skoro domyslnie mamy roboto ustawione, to nie musimy tutaj podawac font-family

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.scss
> +.content{
tak jak pisalam, skorzystajmy ju z tego wrappera ktory mamy w uczestnikach sekcji

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.scss
> +  padding: 30px;
lepiej dac margin;

ogolnie zwiekszmy tez odleglosc mdz wyszukiwarką a listą tych sekcji w tablecie i mobile

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.scss
> +@include breakpoint('laptop') {
nie musisz powielac tych wszystkich styli, wystarczy jak dodasz / zmienisz tylko te, ktore roznia sie od tych, ktore ustaliles powyzej

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.scss
> +    padding: 0px !important;
unikajmy tych important

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.ts
> +  public loadSections() {
public jest domyślne

2023-02-03 09:18 UTC, EMEZYK commented on src/app/features/section/sections.component.ts
> +  ngOnInit() {
wyniosłabym wyżej to ngOnInit, pod stora; jak dla mnie bardziej czytelnie jest wtedy, bo wiem co na starcie się odpala; a wszystkie metody sa ponizej

2023-02-03 09:23 UTC, jBachanek-02 commented on src/app/features/section/sections.component.scss
> +main{
Możemy
obstawiam że mam to zrobić tak ? XD

2023-02-03 09:26 UTC, jBachanek-02 commented on src/app/features/section/sections.component.ts
> +    NgForOf,
zmieniłem na NgFor

2023-02-03 09:27 UTC, jBachanek-02 commented on src/app/features/section/sections.component.html
> +        (activation)="handleActivation(section.id)"
Wiem wiem ale to inny task

2023-02-03 09:28 UTC, jBachanek-02 commented on src/app/features/section/sections.component.html
> +        (activation)="handleActivation(section.id)"
jest do aktywacji i dezaktywacji

2023-02-03 09:30 UTC, jBachanek-02 commented on src/app/features/section/sections.component.scss
> +  padding: 30px;
zrobione

2023-02-03 09:32 UTC, EMEZYK commented on src/app/features/section/sections.component.scss
> +main{
możemy wynieść do oddzielnego taska, aczkolwiek ten będzie zblokowany, dopóki tamten nie będzie zrobiony; więc jak wolisz

2023-02-03 09:33 UTC, jBachanek-02 commented on src/app/features/section/sections.component.scss
> +main{
XD
Możemy wynieść i sobie go przypiszę XD

2023-02-03 09:34 UTC, jBachanek-02 commented on src/app/features/section/sections.component.scss
> +main{
i tak muszę to zrobić i tak XD
a przynajmniej jeden task więcej będzie XD

2023-02-03 09:35 UTC, jBachanek-02 commented on src/app/features/section/sections.component.scss
> +  font-family: var(--roboto);
no w sumie tak zapomniałem

2023-02-03 09:39 UTC, jBachanek-02 commented on src/app/features/section/sections.component.scss
> +@include breakpoint('laptop') {
zrobione

2023-02-03 09:39 UTC, jBachanek-02 commented on src/app/features/section/sections.component.scss
> +    padding: 0px !important;
oks

2023-02-03 09:56 UTC, jBachanek-02 commented on src/app/features/section/sections.component.html
> +        (modification)="handleModification(section.id)"
juz tak

2023-02-03 10:26 UTC, jBachanek-02 commented on src/app/features/section/sections.component.html
> +<main>
Których ?

2023-02-08 09:16 UTC, piodaw requested changes

2023-02-08 09:16 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +import { SectionActions } from '../section';
można to zapisać w jednym imporcie

2023-02-08 09:16 UTC, piodaw commented on src/app/features/home/home.module.ts
>  import { sectionDetailsReducer, sectionReducer } from '../section/store/section.reducer';
importuj z index.ts

2023-02-08 09:16 UTC, piodaw commented on src/app/features/home/home.module.ts
> +import { SectionsComponent } from '../section/sections.component';
jw

2023-02-08 09:16 UTC, piodaw commented on src/app/features/section/sections.component.ts
> +  }
to można od razu zapisać w ngOnInit a jeśli wolisz tak dodaj private

2023-02-08 09:16 UTC, piodaw commented on src/app/features/section/sections.component.html
> +        <ng-container *ngFor="let section of sections">
to można zapisać w jednym ngFor

2023-02-08 13:42 UTC, EMEZYK requested changes

2023-02-08 13:42 UTC, EMEZYK commented on src/app/features/section/sections.component.html
> +          *ngIf="isOwner(section.sectionOwner); else notOwn"
na początku przeczytałam noTown xd  może "notOwner" / 'nonOwner"?

2023-02-08 13:42 UTC, EMEZYK commented on src/app/features/section/sections.component.ts
> +  loggedUserId!: number;
jeśli jest to pole wymagane, to dodaj je do app-sections[]

2023-02-08 13:42 UTC, EMEZYK commented on src/app/features/section/sections.component.ts
> +    this.router.navigate([`/section/${id}`]);
podmień te ścieżki w ten sam sposób jak niżej podales addSection

2023-02-08 13:42 UTC, EMEZYK commented on src/app/features/section/sections.component.ts
> +    this.router.navigate([`section/${id}/edit`]);
jak niżej

2023-02-08 13:42 UTC, EMEZYK commented on src/app/shared/ui/modals/cancel-confirm-dialog/cancel-confirm-dialog.component.html
> +    <button (click)="closeDialog()" mat-button class="cancel-confirm-dialog__cancel-btn error smallButton">
o madonno, jaka klasa :D

2023-02-08 15:00 UTC, jBachanek-02 commented on src/app/shared/ui/modals/cancel-confirm-dialog/cancel-confirm-dialog.component.html
> +    <button (click)="closeDialog()" mat-button class="cancel-confirm-dialog__cancel-btn error smallButton">
to nie moja klasa XD

2023-02-08 15:08 UTC, jBachanek-02 commented on src/app/features/section/sections.component.html
> +          *ngIf="isOwner(section.sectionOwner); else notOwn"
zmieniłem na notOwner

2023-02-08 15:51 UTC, jBachanek-02 commented on src/app/features/section/sections.component.ts
> +    this.router.navigate([`/section/${id}`]);
nie działa XD

2023-02-14 13:29 UTC, akademiaEnvelo approved these changes

2023-02-14 13:29 UTC, akademiaEnvelo commented on src/app/features/section/sections.component.ts
> +  loggedUserId!: number;
zamiast wymuszać działanie kompilatora, możemy po prostu przypisać mu wartość inicjalną

```typescript
loggedUserId$ = this.store.select(selectLoggedUser).subscribe(user => {
      if (user) {
        return user.id;
      } else {
       return null;
      }
    })
 ```
 
 i w templatce najpierw
 ```html
 <ng-container *ngIf="loggedUserId$ | async as userId">
    <app-section-card
          *ngIf=userId === section.user.id; else notOwner">
 </ng-container>
  ```

2023-02-14 14:33 UTC, EMEZYK approved these changes

2023-02-15 08:18 UTC, piodaw approved these changes

2023-02-20 09:37 UTC, merged