FT036-feat-stworzenie-komponentu-listy-kategorii
akademia-envelo-3/meetek-front pull request #86
Opened 2023-01-31 11:32 UTC by damiankubecki

podgląd: https://ft036-feat-stworzenie-komponentu-listy-kategorii--meetek-envelo.netlify.app/theme

2023-02-02 09:51 UTC, EMEZYK requested changes

2023-02-02 09:51 UTC, EMEZYK commented on src/app/shared/ui/category-hashtag-card/category-hashtag-card.component.html
> +    <p [class.narrow]="isModification || isActivityToggle" class="name">{{ name }}</p>
ciekawy zapis!! :)

2023-02-02 09:51 UTC, EMEZYK commented on src/app/shared/ui/category-hashtag-card/category-hashtag-card.component.ts
> +import { BehaviorSubject, debounce, skip, timer } from 'rxjs';
proszę oddzielić importy zewntrzne od wewnetrznych

2023-02-03 07:52 UTC, EMEZYK approved these changes

2023-02-03 07:52 UTC, EMEZYK commented on src/app/shared/hooks/useDestroy.hook.ts
> +export function useDestroy() {
zmienilabym tylko nazwę pliku na use-destroy.hook.ts  zgodnie z konwencją naszego nazewnictwa

2023-02-03 09:17 UTC, jBachanek-02 approved these changes

2023-02-06 09:28 UTC, akademiaEnvelo approved these changes

2023-02-07 12:05 UTC, merged