Ft041 dodanie kolorow dla nieaktywnych buttonow
akademia-envelo-3/meetek-front pull request #87
Opened 2023-01-31 12:30 UTC by jBachanek-02

2023-02-01 08:26 UTC, piodaw approved these changes

2023-02-02 08:10 UTC, lkrzysztoff approved these changes

2023-02-02 08:18 UTC, damiankubecki approved these changes

2023-02-02 08:51 UTC, EMEZYK reviewed
Rekomenduję dodanie  przykladowych przyciskow z tymi stylami do theme

2023-02-02 09:12 UTC, EMEZYK requested changes

2023-02-02 09:12 UTC, EMEZYK commented on src/app/shared/styles/button.scss
> +    padding: 10px 20px;
text-align: center , border-radius i padding powtarzają się dla każdego rodzaju button, moze warto ustawic te wlasciwosci po prostu wyzej dla button, a nie dla kazdego rodzaju z osobna?

2023-02-02 09:31 UTC, jBachanek-02 commented on src/app/shared/styles/button.scss
> +    padding: 10px 20px;
niektóre mają inny padding, 
niektóre nie mają text-align, 
i jeszcze inne nie mają bordera

2023-02-02 09:34 UTC, jBachanek-02 commented on src/app/shared/styles/button.scss
> +    padding: 10px 20px;
dobra zrobione

2023-02-02 09:44 UTC, akademiaEnvelo approved these changes

2023-02-02 09:57 UTC, EMEZYK requested changes

2023-02-02 09:57 UTC, EMEZYK commented on src/app/core/theme.component.ts
> +    <button class="activation">Aktywuj</button>
brak podkreślenia w przyciskach na hover (patrz - przyciski section card)

2023-02-02 09:57 UTC, EMEZYK commented on src/app/core/theme.component.ts
> +    <button class="formButton">Formularze</button>
ten szary background na hover bardzo tutaj nie pasuje; przegadajmy to na kanale i zmienmy

2023-02-02 09:58 UTC, jBachanek-02 commented on src/app/core/theme.component.ts
> +    <button class="formButton">Formularze</button>
proponowałem to już ja cały czas czekam XD

2023-02-02 12:14 UTC, EMEZYK approved these changes

2023-02-02 12:24 UTC, merged