FT050 feat page404
akademia-envelo-3/meetek-front pull request #97
Opened 2023-02-07 10:30 UTC by damiankubecki

podgląd: https://ft050-feat-page404--meetek-envelo.netlify.app/dupa

2023-02-07 14:31 UTC, jBachanek-02 approved these changes

2023-02-08 08:27 UTC, lkrzysztoff approved these changes

2023-02-08 09:24 UTC, piodaw approved these changes
Ok.

2023-02-08 12:57 UTC, EMEZYK requested changes

2023-02-08 12:57 UTC, EMEZYK commented on src/app/features/404/not-found.component.scss
> +    font-weight: normal;
normal jest domyśłny

2023-02-08 12:57 UTC, EMEZYK commented on src/app/app.module.ts
> +import { TokenInterceptorProvider, HttpErrorInterceptorProvider } from '@shared/interceptors';
oddziel importy

2023-02-09 08:00 UTC, damiankubecki commented on src/app/features/404/not-found.component.scss
> +    font-weight: normal;
w nagłówkach domyślny jest `bold`

2023-02-09 08:09 UTC, damiankubecki commented on src/app/app.module.ts
> +import { TokenInterceptorProvider, HttpErrorInterceptorProvider } from '@shared/interceptors';
dlaczego?🤨

2023-02-09 08:11 UTC, EMEZYK commented on src/app/app.module.ts
> +import { TokenInterceptorProvider, HttpErrorInterceptorProvider } from '@shared/interceptors';
ehh, wybacz, jest ok :)

2023-02-09 08:12 UTC, EMEZYK approved these changes

2023-02-10 10:56 UTC, akademiaEnvelo approved these changes

2023-02-13 08:04 UTC, merged