FT053-store-dla-eventów
akademia-envelo-3/meetek-front pull request #98
Opened 2023-02-08 10:13 UTC by EMEZYK

@akademia-envelo-3/meetek-frontend  @KamilWojkowskiEnvelo

2023-02-08 13:22 UTC, piodaw requested changes

2023-02-08 13:22 UTC, piodaw commented on src/app/features/event/store/event.effects.ts
> +import { EventService } from './event.service';
importy do index.ts przerzuć

2023-02-08 13:22 UTC, piodaw commented on src/app/features/section/store/section.service.ts
>  import { API_URL } from '@core/env.token';
rozdziel importy

2023-02-08 13:22 UTC, piodaw commented on src/app/features/section/store/section.actions.ts
> +import { Section } from '@shared/interfaces';
tu też rozdziel

2023-02-08 13:22 UTC, piodaw commented on src/app/features/section/shared/list/list-item/member-list-item.component.ts
> +import { User } from '../../../../../shared/interfaces';
tu też

2023-02-08 13:22 UTC, piodaw commented on src/app/features/event/store/event.effects.ts
> +      }),
tu jak w efekcie wyżej możesz skrócić zapisując bez returna

2023-02-08 13:25 UTC, piodaw requested changes

2023-02-08 13:25 UTC, piodaw commented on src/app/features/event/store/event.reducer.ts
> +  })
skróć zapis

2023-02-08 13:25 UTC, piodaw commented on src/app/features/event/store/event.selectors.ts
> +  return state?.event;
jw

2023-02-09 06:51 UTC, EMEZYK commented on src/app/features/event/store/event.effects.ts
> +import { EventService } from './event.service';
są w index.ts :)  taki zapis niewiele mowi, skad pochodzi plik: import { EventService } from '..'; , wiec wolalam zostawic jak wyzej

2023-02-09 06:51 UTC, EMEZYK commented on src/app/features/event/store/event.effects.ts
> +      }),
racja

2023-02-13 08:24 UTC, damiankubecki commented on src/app/features/event/store/event.service.ts
> +}
czy nie powinniśmy mieć więcej metod do pobierania eventów? Docelowo będziemy pobierać też np. tylko przyszłe, albo tylko przeszłe, na co są/będą osobne endpointy na backendzie

2023-02-14 07:20 UTC, EMEZYK commented on src/app/features/event/store/event.service.ts
> +}
Na spotkaniu ustaliliśmy tylko te dwie metody, tak też jest w tasku. Osoba, która będzie miała później task związany np, z wyswietlaniem przyszłych/przeszłych eventów, po prostu będzie musiała dodać tutaj taką metodę :)

2023-02-14 13:30 UTC, akademiaEnvelo approved these changes

2023-02-15 08:17 UTC, piodaw approved these changes

2023-02-15 11:01 UTC, merged